version: '3'
services:
  base_model_api:
    image: dzigen/base_model_api:v1
    build: ./docker_images/base_modelapi

  model_api:
    image: dzigen/model_api:v1
    build: .
    ports:
      - 4567:4567
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes: 
      - ${PWD}/model_api.log:/home/app/src/logfile.log

  jenkins:
    image: jenkins_with_dockercli:v1
    build: ./docker_images/jenkins_with_dockercli
    ports:
      - 8080:8080
      - 50000:50000
    user: root
    group_add:
      - 0
    volumes:
      - /home/dzigen/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    stdin_open: true # docker run -i
    tty: true        # docker run -t