stages:
  prepare:
    cmd: python src/preprocess.py
    deps:
    - src/preprocess.py
    - data/BankNote_Authentication.csv
    params:
    - prepare.train_size
    - prepare.seed
    outs:
    - data/train_part.csv
    - data/test_part.csv
  
  train:
    cmd: python src/train.py
    deps:
    - src/train.py
    - data/train_part.csv
    params:
    - train.seed
    outs:
    - experiments/model.pkl

  evaluate:
    cmd: python src/predict.py
    deps: 
    - experiments/model.pkl
    - src/predict.py
    - data/test_part.csv
    metrics:
    - experiments/metrics.json:
        cache: false